### ISSUE TITLE
Nightly is no longer working

### ISSUE THREAD

**Issue by eed3si9n** [sbt/sbt-standalone-build#30]
```
[error] Fatal: multiple projects have the same artifacts visible in the same space.
[error]
[error]   org.scala-sbt#zinc-classpath  from sbt212-zinc and sbt212-zinc, both visible in space "sbt212"
[error]   org.scala-sbt#zinc-apiinfo  from sbt212-zinc and sbt212-zinc, both visible in space "sbt212"
[error]   org.scala-sbt#zinc-classfile  from sbt212-zinc and sbt212-zinc, both visible in space "sbt212"
[error]   org.scala-sbt#compiler-bridge  from sbt212-zinc and sbt212-zinc, both visible in space "sbt212"
```

https://github.com/sbt/zinc/pull/576?

**Comment by cunei** [comment]
The PR in https://github.com/sbt/zinc/pull/576 completely changed the way zinc is built, and it took me quite a few days to rework the validation mechanism around it.
The validator should now be fixed by the diff in https://github.com/sbt/sbt-validator/commit/b1201cb6eb9c33728dc62692f6c5bafa19376f80 together with the Jenkins job changes in https://jenkins.scala-sbt.org:8592/job/sbt-validator/jobConfigHistory/showDiffFiles?timestamp1=2018-08-31_07-28-14&timestamp2=2018-09-10_00-29-42

The additional change in https://github.com/sbt/sbt-validator/commit/266f217dd0845cf17b49edefa705423ca24f0882 was needed in order to reinstate the bloopScripted exclusion, in practice reverting https://github.com/sbt/sbt-validator/pull/29/commits/ad970e44f53fdba965ec1751c4e64ca29406ffc6. Currently, the develop branch does not contain `bloopScripted` (removed in https://github.com/sbt/zinc/commit/18af986799e952929148e0305e5337d91bc2d953), but the 1.2.x branch still does; there is test in the Jenkins job which will conditionally define `${vars.excludeBloopIfDefined}` if present. The exclusion is necessary since the subproject introduced a circular dependency sbt->zinc->sbt. I introduced an additional test for commits that are descendants of https://github.com/sbt/zinc/commit/18af986799e952929148e0305e5337d91bc2d953 in https://jenkins.scala-sbt.org:8592/job/sbt-validator/jobConfigHistory/showDiffFiles?timestamp1=2018-09-10_00-29-42&timestamp2=2018-09-10_03-12-41

An additional advantage of the reworked validator is that it will now build in a single step all of the zinc components for 2.10, 2.11, 2.12, and 2.13, as well as `sbt/io` for 2.10, 2.11, 2.12, and the various other subprojects of `sbt/util` and `sbt/librarymanagement` in their supported Scala versions, respectively.

The next step is fixing the community build, along similar lines.
/cc @eed3si9n
